[package]
name = "sink"
version = "0.1.0"
edition = "2024"

[features]
no-dylib = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
uhlc = { version = "0.8", features = ["std"] }
flarrow-api = { workspace = true }
message = { workspace = true }
